import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/layouts/Navbar";
import Footer from "@/component/layouts/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <header className="py-2 md:w-11/12 mx-auto">
          <Navbar></Navbar>
        </header>

        <main className="py-2 md:w-11/12 mx-auto">{children}</main>

        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}